kind: pipeline
type: docker
name: backend

#workspace:
#  path: /drone/src

#platform:
#  arch: amd64
#  os: linux
steps:
  - name: build
    image: golang
    commands:
      - go build
      - echo -n "5.2.6,5.2.4" > .tags
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: username
      password:
        from_secret: password
      repo: foo/bar
#steps:
#  - restore-cache:
#    image: drillster/drone-volume-cache
#    restore: true
#    mount:
#      - ./node_modules
#    volumes:
#      - /tmp/cache:/cache
#  - name: build
#    image: golang
#    commands:
#      - go build -o app
#
#  - name: publish
#    image: plugins/docker
#    settings:
#      username:
#        from_secret: username
#      password:
#        from_secret: password
#      repo: ibangzhao/demo1
#      tags: ["${DRONE_COMMIT_SHA:0:7}","latest" ]
#---
#kind: pipeline
#type: docker
#name: frontend
#
#platform:
#  arch: arm64
#
#steps:
#  - name: build
#    image: node
#    commands:
#      - npm install
#      - npm test
#---
#kind: pipeline
#name: after
#steps:
#  - name: notify
#    image: plugins/slack
#    settings:
#      room: general
#      webho:
#
#trigger:
#  branch:
#    include:
#      - master
#    exclude:
#      - master
#  event:
#    - push